# Generated by Django 4.2.6 on 2023-10-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('publicationyear', models.CharField(max_length=4)),
                ('isbn', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
